
version: '3'

services:
  todosDB:
    image: postgres:15.3
    container_name: english-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=GalletasMarias
      - POSTGRES_PASSWORD=GalletasMarias
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    
      